name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - 'assets/**'
      - '**/*.gitignore'
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: false
          go-version-file: go.mod
      - name: Build
        run: make build